apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec: # todas as especificações do objeto, cada objeto tem um spec diferente!
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template: # estrutura do pod
    metadata:
      labels:
        app: postgre
    spec: # especificação do pod
      automountServiceAccountToken: false
      containers:
        - name: postgre
          image: postgres:16.3 
          env:
            - name: POSTGRES_PASSWORD
              value:  P@ssw0rd2024!
            - name: POSTGRES_USER
              value: reviewFilmes
            - name: POSTGRES_DB
              value: reviewfilmes
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    # targetPort: 5432
