apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewfilmes
spec:
  selector:
    matchLabels:
      app: reviewfilmes
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:
      - name: reviewfilmes
        image: yg/review-filmes:v1
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgre;Database=reviewfilmes;Username=reviewFilmes;Password=P@ssw0rd2024!"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          
---

apiVersion: v1
kind: Service
metadata:
  name: reviewfilmes
spec:
  selector:
    app: reviewfilmes
  ports:
  - port: 80 # redireciona para a porta 80, não é necessário colocar a porta no browser!
    targetPort: 8080 # vai para a porta 8080 do service
    nodePort: 30000 # apenas para funcionar local, pois quando você cria a service ele coloca uma porta aleatória do range
  type: NodePort
